- name: Test ping host with group web
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  - name: Git checkout
    ping:
  - name: Install nginx httpd (state=present is optional)
    apt:
      name: nginx
      state: present
  - name: Change file ownership, group and permissions
    file:
      path: /home/max
      state: directory
