- name: Test ping host with group web
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  - name: Git checkout
    ping:
  - name: Install nginx httpd (state=present is optional)
    apt:
      name: nginx
      state: present
  - name: Change file ownership, group and permissions
    file:
      path: /home/max
      state: directory
  - name: Download foo.conf
    get_url:
      url: https://nodejs.org/dist/v14.17.6/node-v14.17.6-linux-x64.tar.xz
      dest: /opt/node.tar.xz
  - name: Extract foo.tgz into /var/lib/foo
    ansible.builtin.unarchive:
      src: /opt/node.tar.xz
      dest: /opt
      remote_src: yes
